export const TRANSLATIONS = {
  en: {
    chooseSubject: "Choose Your Subject",
    selectSubject: "Select a subject to start your learning journey",
    class: "Class",
    age: "Age",
    learningGoal: "Your Learning Goal",
    interactiveNotes: "📚 Interactive Notes will help in studies",
    smartQuizzes: "🧠 Smart Quizzes will improve in question solving",
    funGames: "🎮 Fun Games",
    // UI-wide labels
    topicsNotes: "Topics & Notes",
    seeWhatYouveLearnt: "See What You've Learnt",
    timeToPlay: "Time to Play",
    topicsForClassPrefix: "Topics for Class ",
    clickAnyTopic: "Click on any topic to view detailed notes and explanations",
    readNotes: "Read Notes",
    noTopicsAvailableHeading: "No Topics Available",
    noTopicsAvailableBody: "Topics for {subject} in Class {classLevel} are coming soon!",
    quickReviewNotes: "Quick Review Notes",
    keyPointsToRemember: "Key Points to Remember",
    quickTip: "💡 Quick Tip",
    practiceTip: "Practice this topic regularly to build strong fundamentals for advanced concepts.",
    focusArea: "🎯 Focus Area",
    focusAreaBody: "Understanding this concept will help you excel in related topics and exams.",
    takePracticeQuiz: "Take Practice Quiz",
    viewRelatedTopics: "View Related Topics",
    // Onboarding
    letsGetStarted: "Let's Get Started!",
    selectYourClass: "Select Your Class",
    whatsYourName: "What's Your Name?",
    howOldAreYou: "How Old Are You?",
    whyDoYouWantToLearn: "Why Do You Want to Learn?",
    chooseClassHint: "Choose your current class level to get personalized content",
    enterYourName: "Enter your name",
    enterYourAge: "Enter your age",
    enterReasonPlaceholder: "I want to improve my grades, learn new concepts, prepare for exams...",
    back: "Back",
    next: "Next",
    startLearning: "Start Learning!",
    // translate UI labels
    translateTitle: "Translate",
    originalLang: "Original language",
    targetLang: "Target language",
    enterOriginal: "Enter text in original language",
    enterOriginalPlaceholder: "Type here...",
    translate: "Translate",
    translating: "Translating...",
    translateFailed: "Translation failed",
    clear: "Clear",
    copy: "Copy",
  },
  hi: {
    chooseSubject: "अपना विषय चुनें",
    selectSubject: "अपनी शिक्षण यात्रा शुरू करने के लिए विषय चुनें",
    class: "कक्षा",
    age: "आयु",
    learningGoal: "आपका शिक्षण लक्ष्य",
    interactiveNotes: "📚 इंटरएक्टिव नोट्स पढ़ाई में मदद करेंगे",
    smartQuizzes: "🧠 स्मार्ट क्विज़ प्रश्न हल करने में सुधार करेंगे",
    funGames: "🎮 मज़ेदार खेल",
    // UI-wide labels
    topicsNotes: "विषय और नोट्स",
    seeWhatYouveLearnt: "आपने क्या सीखा देखें",
    timeToPlay: "खेलने का समय",
    topicsForClassPrefix: "कक्षा के लिए विषय ",
    clickAnyTopic: "विस्तृत नोट्स और व्याख्या देखने के लिए किसी भी विषय पर क्लिक करें",
    readNotes: "नोट्स पढ़ें",
    noTopicsAvailableHeading: "कोई विषय उपलब्ध नहीं है",
    noTopicsAvailableBodyPrefix: "विषयों के लिए ",
    quickReviewNotes: "त्वरित समीक्षा नोट्स",
    keyPointsToRemember: "याद रखने के लिए मुख्य बिंदु",
    quickTip: "💡 त्वरित सुझाव",
    focusArea: "🎯 ध्यान क्षेत्र",
    takePracticeQuiz: "प्रैक्टिस क्विज़ लें",
    viewRelatedTopics: "संबंधित विषय देखें",
    // Onboarding
    letsGetStarted: "चलो शुरू करें!",
    selectYourClass: "अपनी कक्षा चुनें",
    whatsYourName: "आपका नाम क्या है?",
    howOldAreYou: "आप कितने वर्ष के हैं?",
    whyDoYouWantToLearn: "आप सीखना क्यों चाहते हैं?",
    chooseClassHint: "निजीकृत सामग्री प्राप्त करने के लिए अपनी वर्तमान कक्षा स्तर चुनें",
    enterYourName: "अपना नाम दर्ज करें",
    enterYourAge: "अपना उम्र दर्ज करें",
    enterReasonPlaceholder: "मैं अपने ग्रेड बेहतर करना चाहता/चाहती हूं, नए कॉन्सेप्ट सीखना चाहता/चाहती हूं, परीक्षाओं की तैयारी...",
    back: "वापस",
    next: "आगे",
    startLearning: "शुरू करें!",
    // translate UI labels
    translateTitle: "अनुवाद",
    originalLang: "मूल भाषा",
    targetLang: "लक्ष्य भाषा",
    enterOriginal: "मूल भाषा में पाठ दर्ज करें",
    enterOriginalPlaceholder: "यहाँ लिखें...",
    translate: "अनुवाद",
    translating: "अनुवाद हो रहा है...",
    translateFailed: "अनुवाद विफल हुआ",
    clear: "साफ करें",
    copy: "कॉपी करें",
  },
  ta: {
    chooseSubject: "உங்கள் பாடத்தை தேர்வுசெய்யவும்",
    selectSubject: "உங்கள் பயில்நெறியை தொடங்க ஒரு பாடத்தை தேர்வுசெய்யவும்",
    class: "வகுப்பு",
    age: "வயது",
    learningGoal: "உங்கள் கல்வி இலக்கு",
    interactiveNotes: "📚 ஊக்கமளிக்கும் குறிப்புகள் படிப்பில் உதவும்",
    smartQuizzes: "🧠 புத்திசாலி வினாக்குறிகள் கேள்வி பதில் திறனை மேம்படுத்தும்",
    funGames: "🎮 சுவாரஷ்ய விளையாட்டுகள்",
    // UI-wide labels
    topicsNotes: "தலைப்புகள் மற்றும் குறிப்புகள்",
    seeWhatYouveLearnt: "நீங்கள் என்ன கற்றுக்கொண்டீர்கள் என்பதைப் பார்க்கவும்",
    timeToPlay: "விளையாட நேரம்",
    topicsForClassPrefix: "வகுப்புக்கான தலைப்புகள் ",
    clickAnyTopic: "விரிவான குறிப்புகள் மற்றும் விளக்கங்களை காண எதாவது தலைப்பில் கிளிக் செய்யவும்",
    readNotes: "குறிப்புகளைப் படிக்கவும்",
    noTopicsAvailableHeading: "தலைப்புகள் இல்லை",
    noTopicsAvailableBodyPrefix: "வகுப்புக்கான தலைப்புகள் ",
    quickReviewNotes: "விரைவு மதிப்பீட்டு குறிப்புகள்",
    keyPointsToRemember: "முக்கிய குறிப்புகள்",
    quickTip: "💡 தகவல்",
    focusArea: "🎯 கவனம் செலுத்த வேண்டிய பகுதிகள்",
    takePracticeQuiz: "பயிற்சி வினாக்கள்",
    viewRelatedTopics: "பொருத்தமான தலைப்புகளைக் காண்க",
    // Onboarding
    letsGetStarted: "துவங்கலாம்!",
    selectYourClass: "உங்கள் வகுப்பை தேர்வுசெய்க",
    whatsYourName: "உங்கள் பெயர் என்ன?",
    howOldAreYou: "உங்களுக்கு வயது எத்தனை?",
    whyDoYouWantToLearn: "நீங்கள் ஒன்றை கற்றுக்கொள்ள விரும்புகிறீர்கள் எந்த காரணத்தால்?",
    chooseClassHint: "தனிப்பயன் உள்ளடக்கம் பெற உங்கள் தற்போதைய வகுப்பு நிலை தேர்வுசெய்க",
    enterYourName: "உங்கள் பெயரை உள்ளிடவும்",
    enterYourAge: "உங்கள் வயதை உள்ளிடவும்",
    enterReasonPlaceholder: "நான் என் தரங்களை மேம்படுத்த விரும்புகிறேன், புதிய கருத்துக்களை கற்றுக்கொள்ள விரும்புகிறேன், தேர்வுகளுக்கு தயாராக...",
    back: "மறுபக்கம்",
    next: "அடுத்தது",
    startLearning: "கற்றல் துவங்கவும்!",
    // translate UI labels
    translateTitle: "மொழிபெயர்ப்பு",
    originalLang: "மூல மொழி",
    targetLang: "இலக்கு மொழி",
    enterOriginal: "மூல மொழியிலான உரையை உள்ளிடவும்",
    enterOriginalPlaceholder: "இங்கே டைப் செய்யவும்...",
    translate: "மொழிபெயர்ப்பு",
    translating: "மொழிபெயர்ப்பு நடைபெறுகிறது...",
    translateFailed: "மொழிபெயர்ப்பு தோல்வியடைந்தது",
    clear: "அழிக்கவும்",
    copy: "பகிர்",
  },
  te: {
    chooseSubject: "మీ విషయం ఎంచుకోండి",
    selectSubject: "మీ అభ్యాస ప్రయాణాన్ని ప్రారంభించేందుకు విషయాన్ని ఎంచుకోండి",
    class: "తరగతి",
    age: "వయస్సు",
    learningGoal: "మీ అభ్యాస లక్ష్యం",
    interactiveNotes: "📚 ఇంటరాక్టివ్ నోట్స్ చదువులో సహాయపడతాయి",
    smartQuizzes: "🧠 స్మార్ట్ క్విజ్‌లు ప్రశ్నలు పరిష్కరించడాన్ని మెరుగుపరుస్తాయి",
    funGames: "🎮 సరదా ఆటలు",
    // UI-wide labels (fallback to English for Telugu)
    topicsNotes: "Topics & Notes",
    seeWhatYouveLearnt: "See What You've Learnt",
    timeToPlay: "Time to Play",
    topicsForClassPrefix: "Topics for Class ",
    clickAnyTopic: "Click on any topic to view detailed notes and explanations",
    readNotes: "Read Notes",
    noTopicsAvailableHeading: "No Topics Available",
    noTopicsAvailableBodyPrefix: "Topics for ",
    quickReviewNotes: "Quick Review Notes",
    keyPointsToRemember: "Key Points to Remember",
    quickTip: "💡 Quick Tip",
    focusArea: "🎯 Focus Area",
    takePracticeQuiz: "Take Practice Quiz",
    viewRelatedTopics: "View Related Topics",
    // Onboarding (fallback English)
    letsGetStarted: "Let's Get Started!",
    selectYourClass: "Select Your Class",
    whatsYourName: "What's Your Name?",
    howOldAreYou: "How Old Are You?",
    whyDoYouWantToLearn: "Why Do You Want to Learn?",
    chooseClassHint: "Choose your current class level to get personalized content",
    enterYourName: "Enter your name",
    enterYourAge: "Enter your age",
    enterReasonPlaceholder: "I want to improve my grades, learn new concepts, prepare for exams...",
    back: "Back",
    next: "Next",
    startLearning: "Start Learning!",
    // translate UI labels
    translateTitle: "Translate",
    originalLang: "Original language",
    targetLang: "Target language",
    enterOriginal: "Enter text in original language",
    enterOriginalPlaceholder: "Type here...",
    translate: "Translate",
    translating: "Translating...",
    translateFailed: "Translation failed",
    clear: "Clear",
    copy: "Copy"
  }
}
